### PR TITLE
mscorlib and System.Xml additions

### PR DESCRIPTION
**Pull request by lemonmojo**
New bindings for mscorlib, System.Core, System.Xml and System.Data types

## mscorlib
System.Attribute
System.Collections.ICollection
System.Collections.IDictionary
System.Runtime.InteropServices._Attribute
System.Runtime.Serialization.IDeserializationCallback
System.IComparable
System.IComparable\`1
System.Tuple
System.Tuple\`1
System.Tuple\`2
System.Tuple\`3
System.Tuple\`4
System.Tuple\`5
System.Tuple\`6
System.Tuple\`7
System.Tuple\`8
System.TupleExtensions

## System.Core
System.Collections.Generic.HashSet\`1

## System.Xml
System.Xml.Serialization.IXmlSerializable
System.Xml.Serialization.XmlSerializer
System.Xml.Schema.XmlSchema
System.Xml.XmlReader
System.Xml.XmlReaderSettings
System.Xml.XmlWriter
System.Xml.XmlWriterSettings

## System.Data
System.Data.DataColumn
System.Data.DataColumnChangeEventArgs
System.Data.DataColumnChangeEventHandler
System.Data.DataColumnCollection
System.Data.DataException
System.Data.DataRelation
System.Data.DataRelationCollection
System.Data.DataRow
System.Data.DataRowAction
System.Data.DataRowBuilder
System.Data.DataRowChangeEventArgs
System.Data.DataRowChangeEventHandler
System.Data.DataRowCollection
System.Data.DataRowState
System.Data.DataRowVersion
System.Data.DataRowView
System.Data.DataSet
System.Data.DataSetDateTime
System.Data.DataSetSchemaImporterExtension
System.Data.DataSysDescriptionAttribute
System.Data.DataTable
System.Data.DataTableClearEventArgs
System.Data.DataTableClearEventHandler
System.Data.DataTableCollection
System.Data.DataTableNewRowEventArgs
System.Data.DataTableNewRowEventHandler
System.Data.DataTableReader
System.Data.DataView
System.Data.DataViewManager
System.Data.DataViewRowState
System.Data.DataViewSetting
System.Data.DataViewSettingCollection

### CODE REVIEW

**Comment by lemonmojo** [comment]
Hey guys! Have you got a chance to review this PR? Any issues or anything you'd want me to change?

**Comment by KosmicTask** [comment]
Will hopefully get a look by next week. It’s on the list!

**Comment by lemonmojo** [comment]
@KosmicTask I'd like to discuss some other things in regards to Dubrovnik which I think will be overkill to do via Github issues. Do you guys have a Slack channel or Gitter or something like that where we could get a discussion started? Or even just an email address...

**Comment by KosmicTask** [comment]
we have now

https://gitter.im/ThesaurusSoftware/community#

**Comment by KosmicTask** [comment]
merged

**Pull request closed without merging**
